### ISSUE TITLE
deleteArchive() causes interface error

### ISSUE THREAD

**Issue by LoganLehman** [opentok/OpenTok-PHP-SDK#192] opened 2017-08-04 20:37 UTC
Hello,

When calling deleteArchive from the OpenTok class, I am getting the following error:

FatalThrowableError in Client.php line 189:
Cannot instantiate interface OpenTok\Exception\Exception
in Client.php line 189
at Client->handleException(object(RuntimeException)) in Client.php line 122
at Client->deleteArchive('916d1f9e-0661-4764-9fb5-406d9f3764cb') in OpenTok.php line 364
at OpenTok->deleteArchive('916d1f9e-0661-4764-9fb5-406d9f3764cb') in VideoRTC.php line 40

Any ideas?

I am using PHP 7, Laravel 5.4, and OpenTok v2.3.2

**Comment by logan-jobzmall** [comment] 2017-08-21 23:20
@aiham ?

**Comment by aiham** [comment] 2017-08-22 00:00
@logan-jobzmall Sorry not sure how I missed this 17 days ago. I'll take a look.

**Comment by logan-jobzmall** [comment] 2017-08-22 19:40
@aiham Awesome! Thank you so much. It would help a lot as we are currently unable to prune videos in our S3 bucket.

**Comment by marcioaffonso** [comment] 2018-01-15 11:10
@logan-jobzmall, sorry for the delay. One thing I've noticed is that the lines of the errors in your stack trace do not coincide with the lines of the actual source code. Not sure if this was somehow modified on our side or on your side, but I've tried to reproduce the error with both the 2.3.2 version (which you mentioned) and the current version (3.1) and everything seems to be working fine.
Can you tell me if this is still an issue?

**Comment by aiham** [comment] 2018-01-16 02:31
@logan-jobzmall This was fixed on 12 August 2016 and should be included from v2.4.0 onwards: https://github.com/opentok/OpenTok-PHP-SDK/commit/d2a4bd6#diff-cd751004cbc618902aa02ae2aed35fbeL189 by referencing the global `\Exception` rather than the `Opentok\Exception\Exception`.

Please use the latest version of the PHP SDK, thanks.

**Closed by aiham** 2018-01-16 02:31 UTC
